# Generated by Django 4.2.1 on 2023-05-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
