# Generated by Django 4.2.1 on 2023-05-22 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=uuid.UUID('00a5559f-6e24-493f-953d-80a6839ccd79')),
        ),
    ]
