# Generated by Django 4.2.1 on 2023-05-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_customuser_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
